name: Generate Static Routes

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate routes.json
        run: node generateRoutesManifest.js

      - name: Commit and push to static branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B static
          git add routes.json
          git commit -m "Auto-generate routes.json"
          git push origin static --force